x-args: &args
  BUILD_VOICE_SUPPORT: OFF
  CMAKE_BUILD_TYPE: Release
  DPP_VERSION: master
x-test: &test
  command: /test/test.sh
  volumes:
    - ./test:/test:ro 

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      args: *args
    <<: *test
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args: *args
    <<: *test
